package it.polimi.ingsw.model.player;

public enum PlayerStatus {
    IDLE,
    SELECTING_DESTINATION_AFTER_MARKET,
    SELECTING_CONVERSION,
    SELECTING_BUY_RESOURCES,
    SELECTING_QM,
    SELECTING_PRODUCTION_RESOURCES
}
