package it.polimi.ingsw.view.gui;

public enum GuiStatus {
    IDLE,
    SELECTING_THE_SLOT,
    SELECTING_DEST_AFTER_MARKET,
    SELECTING_DESTINATION_AFTER_MARKET,
    SELECTING_CONVERSION,
    SELECTING_BUY_RESOURCES,
    SELECTING_QM,
    SELECTING_PRODUCTION_RESOURCES
}
