package it.polimi.ingsw.view.gui;

public enum GuiStatus {
    IDLE,
    SELECTING_PROD_SLOT,
    SELECTING_CARD_SLOT,
    SELECTING_DEST_AFTER_MARKET,
    SELECTING_CONVERSION,
    SELECTING_PAY_RESOURCES,
    SELECTING_QM,
}
